### ISSUE TITLE
Deploy automatycally on a website (staging/prod) 

### ISSUE THREAD

**Issue by Ouarzy** [HackYourJob/HackYourTraining#2]
We should see our site alive as soon as possible to show our work to the community.

We should manage 2 urls:
* one for a staging site (continuous deployment)
* one for a production site

**Comment by Ouarzy** [comment]
How does it works to deploy?

**Comment by fpellet** [comment]
Ready for production site (each commit on master)
I think that we haven't need staging site

**Comment by Ouarzy** [comment]
Ok maybe we don't need staging yet, but it doesn't look like any commit on master is automaticaly published? I probably missed something?

**Comment by fpellet** [comment]
Yes, it's work normally, but currently, last version not build :( (Tab in fs source)

**Comment by Ouarzy** [comment]
Yep, my bad! :)

**Comment by devcrafting** [comment]
Done with https://github.com/HackYourJob/GitHubPublisher that handle push on this repo, and deploy master branch in a Docker container on server.
It relies on Dockerfile and publish.sh in this repo.
