### ISSUE TITLE
Trainer confirmation form

### ISSUE THREAD

**Issue by Ouarzy** [HackYourJob/HackYourTraining#5]
When 15 people have registered as "interested by the training", the trainer receives a tweet with the url of the potential training page.

He is the only one to see a confirmation form, where he could :
* say he's not interested
* say he's interested

If interested he has to provide:
* the price per trainee
* the minimum and maximum possible trainees
* a date 
* a duration

In any case we provide a empty free text field to collect any feedback.

**Comment by devcrafting** [comment]
Google form for now : https://docs.google.com/forms/d/1BxS49dHKZMRmIfr4K_BXNCFaq0GsFBnb_K2kW5FrrSs/viewform
With a page on the site to anwser the community's request.

**Comment by devcrafting** [comment]
Proposed tweet for the Greg Young proposal:
"Hi @gregyoung, community (via @Ouarzy) is interested in a CQRS/ES training in Lyon around september, see https://www.hackyourtraining.com/2016-09-Lyon-GregYoung-CQRS-ES/answerRequest"
NB: the link is provided through #12

**Comment by devcrafting** [comment]
Tweeted https://twitter.com/HackYrTraining/status/751448840935530496
