### ISSUE TITLE
Make clearer the fact that registration is not a commitment to the training

### ISSUE THREAD

**Issue by Ouarzy** [HackYourJob/HackYourTraining#9]
From an interesting feedback of lilobase on the slack.

We could:
- Change the "register" button by "I'm interested"
- Add a little explanation to say first we want to show interest for a topic, and then try to find a way to make it happen with the potential trainer

... Any other idea welcome

**Comment by devcrafting** [comment]
+1 we can do it with @fpellet now :)

**Comment by Ouarzy** [comment]
Seems better to me :)
